<?php

  /**
 * Implements hook_ctools_plugin_directory().
 *
 * @param string $owner
 *   The system name of the module owning the plugin type for which a base
 *   directory location is being requested.
 *
 * @param string $plugin_type
 *   The name of the plugin type for which a base directory is being requested.
 *
 * @return path
 *   The path where CTools' plugin system should search for plugin files,
 *   relative to your module's root. Omit leading and trailing slashes.
 */
function vs_checkout_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' &&  in_array($plugin_type, array('content_types'))) {
    return 'plugins/' . $plugin_type;
  }
}

function vs_checkout_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_form_commerce_cart_form_default' && arg(0) == 'checkout') {
    unset($form['actions']);
  }
  if ($form_id == 'user_login_block' && arg(0) == 'checkout') {
    $form['#theme'] = 'vs_checkout_login_user';
    $form['actions']['submit']['#value'] = 'Войти и заказать'; 
    $form['name']['#title'] = 'Имя пользователя';
    $form['pass']['#title'] = 'Пароль';
    $form['actions']['submit']['#attributes']['class'] = array('btn-40', 'small', 'ui-loader');
    $form['actions']['continue_guest'] = array(
      '#type' => 'button',
      '#value' => 'Continue as guest'
    );
    dsm($form);
  }
}

function vs_checkout_theme() {
  return array(
    'vs_checkout_login_user' => array(
      'path' => drupal_get_path('module', 'vs_checkout') . '/theme',
      'template' => 'vs-checkout-login-user',
      'render element' => 'form',
    ),
  );
}