<?php

  /**
 * Implements hook_ctools_plugin_directory().
 *
 * @param string $owner
 *   The system name of the module owning the plugin type for which a base
 *   directory location is being requested.
 *
 * @param string $plugin_type
 *   The name of the plugin type for which a base directory is being requested.
 *
 * @return path
 *   The path where CTools' plugin system should search for plugin files,
 *   relative to your module's root. Omit leading and trailing slashes.
 */
function vs_checkout_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' &&  in_array($plugin_type, array('content_types'))) {
    return 'plugins/' . $plugin_type;
  }
}

function vs_checkout_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_form_commerce_cart_form_default' && arg(0) == 'checkout') {
    unset($form['actions']);
  }
  if ($form_id == 'user_login_block' && arg(0) == 'checkout') {
    $form['#theme'] = 'vs_checkout_login_user';
    $form['actions']['submit']['#value'] = 'Войти и заказать';
    $form['actions']['submit']['#ajax']['callback'] = 'vs_checkout_login_ajax';
//    $form['actions']['submit']['#ajax']['event'] = 'vs_checkout_login_ajax';
    $form['name']['#title'] = 'Имя пользователя';
    $form['pass']['#title'] = 'Пароль';
    $form['actions']['continue_guest'] = array(
      '#type' => 'button',
      '#value' => 'Continue as guest',
      '#ajax' => array(
        'callback' => 'vs_checkout_guest_ajax',
      ),
    );
  }
  if ($form_id == 'commerce_checkout_form_checkout') {
    $form['#theme'] = 'vs_checkout_billing_information';
  }
}

function vs_checkout_theme() {
  return array(
    'vs_checkout_login_user' => array(
      'path' => drupal_get_path('module', 'vs_checkout') . '/theme',
      'template' => 'vs-checkout-login-user',
      'render element' => 'form',
    ),
    'vs_checkout_billing_information' => array(
      'path' => drupal_get_path('module', 'vs_checkout') . '/theme',
      'template' => 'vs-checkout-billing-information',
      'render element' => 'form',
    ),
  );
}

function vs_checkout_login_ajax($form, &$form_state){
  global $user;
  if ($user->uid != 0) {
    $commands[] = ajax_command_invoke('#checkoutPanel', 'addClass', array('element-hidden'));
  }
  else {
    $commands[] = ajax_command_invoke('#checkoutPanel input', 'addClass', array('error'));
    $commands[] = ajax_command_invoke('.vs-signin-error-msg', 'css', array('display', 'block'));
    $commands[] = ajax_command_remove('.vs-ajax-submit-throbber');
  }
  
  return array('#type' => 'ajax', '#commands' => $commands);  
}

function vs_checkout_guest_ajax($form, &$form_state) {
//  $commands[] = ajax_command_remove($wrapper);
  return array('#type' => 'ajax', '#commands' => $commands);  
}