<?php

  /**
 * Implements hook_ctools_plugin_directory().
 *
 * @param string $owner
 *   The system name of the module owning the plugin type for which a base
 *   directory location is being requested.
 *
 * @param string $plugin_type
 *   The name of the plugin type for which a base directory is being requested.
 *
 * @return path
 *   The path where CTools' plugin system should search for plugin files,
 *   relative to your module's root. Omit leading and trailing slashes.
 */
function vs_categories_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' &&  in_array($plugin_type, array('content_types'))) {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme.
 */
function vs_categories_theme() {
  return array(
    'vs_sidebar_instock_menu' => array(
      'path' => drupal_get_path('module', 'vs_categories') . '/themes',
      'template' => 'vs-sidebar-instock-menu',
    ),
    'vs_category_page_content' => array(
      'path' => drupal_get_path('module', 'vs_categories') . '/themes',
      'template' => 'vs-category-page-content',
    ),
    'vs_categories_footer' =>array(
      'variables' => array(),  
    ),
  );
}

function vs_categories_block_info() {
  $blocks = array();
  
  // This example comes from node.module.
  $blocks['footer'] = array(
    'info' => t('Footer'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}

function vs_categories_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'footer':
      $block['subject'] = t('Footer');
      $block['content'] = theme('vs_categories_footer', array('vs_categories_footer', 'vid' => 4));
      break;

  }

  return $block;
}

function theme_vs_categories_footer(&$vars){
  $first_line = array();
  $second_line = array();
  $html = '';
  
  $terms = taxonomy_get_tree($vars['vid'], 0, 1);
  // Sort content to first and second line.
  foreach ($terms as $term) {
    $term = taxonomy_term_load($term->tid);
    if (empty($term->field_footer_link)) {
      $second_line[] = $term;
    }else {
      $term_link = format_string($term->field_footer_link[LANGUAGE_NONE][0]['value'], array('!SizePopup' => '<a class="popup-sizes" href="/popup/sizes">' . $term->name . '</a>'));
      if ($term_link == $term->field_footer_link[LANGUAGE_NONE][0]['value']) {
        $term_link = l($term->name, $term->field_footer_link['und'][0]['value']);
      }
      $first_line[] = $term_link;
    }
  }
  if (!empty($first_line)) {
    $html .= '<ul class="footer-first-line">';
    foreach ($first_line as $term) {
      $html .= '<li>' . $term . '</li>';
    }
    $html .= '</ul>';
  }
  $html .= '<div class="clearfix"></div>';
  if (!empty($second_line)) {
    $html .= '<ul class="footer-second-line">';
    foreach ($second_line as $term) {
      $html .= '<li>' . $term->name . '</li>';
    }
    $html .= '</ul>';
  }
  return $html;
}

function vs_categories_preprocess_page(&$vars) {
  unset($vars['page']['footer']['system_powered-by']);
  $block = module_invoke('vs_categories', 'block_view', 'footer');
  $vars['page']['footer']['#markup'] = $block['content'];
}

function vs_categories_preprocess_views_view(&$vars) {
  drupal_add_library('system', 'ui.accordion');
  drupal_add_js(drupal_get_path('theme', 'victoria') . '/scripts/vs-category.js');

}