<?php

  /**
 * Implements hook_ctools_plugin_directory().
 *
 * @param string $owner
 *   The system name of the module owning the plugin type for which a base
 *   directory location is being requested.
 *
 * @param string $plugin_type
 *   The name of the plugin type for which a base directory is being requested.
 *
 * @return path
 *   The path where CTools' plugin system should search for plugin files,
 *   relative to your module's root. Omit leading and trailing slashes.
 */
function vs_categories_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' &&  in_array($plugin_type, array('content_types'))) {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme.
 */
function vs_categories_theme() {
  return array(
    'vs_sidebar_instock_menu' => array(
      'path' => drupal_get_path('module', 'vs_categories') . '/themes',
      'template' => 'vs-sidebar-instock-menu',
    ),
    'vs_category_page_content' => array(
      'path' => drupal_get_path('module', 'vs_categories') . '/themes',
      'template' => 'vs-category-page-content',
    ),
  );
}