-1!=window.location.href.indexOf("commerce2/signin/topc")&&!0==VSD.ABTesting.is("clicktochat")&&$.getScript("https://www.livelook.com/services/llfm/FMSet.aspx?siteid=RNCH:SC30814858:US:1");
function vsPopUp(a,e,b){var d=-1==a.indexOf(".com"),g=d?0:document.location.hostname!=a.split("/",3)[2];"secure.victoriassecret.com"==window.location.hostname&&(g=!1);if(g){var f={windowSm:{height:500,width:380,createnew:0,status:1},windowMed:{height:500,width:489,createnew:0,status:1},windowLrg:{height:500,width:600,createnew:0,status:1},windowXlrg:{height:768,width:768,createnew:0,status:1,scrollbars:0},windowAltView:{height:640,width:460,createnew:0,status:1,scrollbars:0},windowAllStyles:{height:520,
width:490,createnew:0,status:1},windowCenter:{height:300,width:400,createnew:0,center:1},windowNotNew:{height:300,width:400,center:1,createnew:0},windowSASCls:{height:542,width:500,createNew:0,scrollbars:0},facebook:{height:542,width:500,createNew:0,scrollbars:0},twitter:{height:542,width:800,createNew:0,scrollbars:0}},g=1,c,h;h=e.split(",");c={height:500,width:380,toolbar:0,scrollbars:1,status:0,resizable:1,left:20,top:20,center:0,createnew:1,location:0,menubar:0,emailTitle:"",emailContent:"",twitterContent:""};
c=jQuery.extend(c,b);if("facebook"==e)c.file="http://www.facebook.com/sharer.php?u="+a;else if("twitter"==e)c.file="http://twitter.com/home?status="+c.twitterContent;else{if("email"==e)return window.location="mailto:?subject="+c.emailTitle+"&body="+c.emailContent,!0;c.file=a}if(1==h.length&&1==h[0].split(":").length)h=h[0],"undefined"!=typeof f[h]&&(c=jQuery.extend(c,f[h]));else for(b=0;b<h.length;b++)e=h[b].split(":"),"undefined"!=typeof c[e[0]]&&2==e.length&&(c[e[0]]=e[1]);1==c.center&&(c.top=(screen.height-
(c.height+110))/2,c.left=(screen.width-c.width)/2);h=window.open(c.file,c.createnew?"PopUpWindow"+g:"PopUpWindow","location="+c.location+",menubar="+c.menubar+",height="+c.height+",width="+c.width+",toolbar="+c.toolbar+",scrollbars="+c.scrollbars+",status="+c.status+",resizable="+c.resizable+",left="+c.left+",screenX="+c.left+",top="+c.top+",screenY="+c.top);h.resizeTo(c.width+8,c.height+80);h.focus();g+=1}else VSD.Overlay.open({title:!0,titleText:"",closeButton:!0,modal:!0,overlayAddClass:"overlay-popup "+
e,content:function(){d||(a=("https:"==document.location.protocol?VSD.swww:VSD.www)+a.split(".com",2)[1]);$.get(a,function(a){if(0<a.length){var a="https:"==document.location.protocol?a.replace(/http/g,"https"):a,b=document.createElement("div");b.innerHTML=a;b=b.getElementsByTagName("div")[0];$(".content-inner",VSD.Overlay.id).html(b).find("div:first").addClass("popup-content")}1===$(".content-inner #altview-container img",VSD.Overlay.id).length&&$(".content-inner #altview-container img",VSD.Overlay.id).load(function(){$(VSD.Overlay.id).addClass("flex-size");
var a=$(VSD.Overlay.id).height();VSD.Overlay.center(a)});0<$("#ImgSwapMain").length?($(".item > a, .alt-image-bottom",VSD.Overlay.id).imgSwap({layout:"bottom"}),$(".item > a, .alt-image-right",VSD.Overlay.id).imgSwap({layout:"right",tooltip:!0})):0<$(".tab_container",VSD.Overlay.id).length&&($(".tab_content").hide(),$("ul.tab li").click(function(a){a.preventDefault();a=$(this).parents(".tab-wrapper");a.find("li").removeClass("active");$(this).addClass("active");$(".tab_content",a).hide();var a=$(this).find("a").attr("href"),
a=a.split("#"),b=a.length;b--;a=a[b];$("#"+a).show();setTimeout(function(){VSD.UI.scrollbar(VSD.Overlay.content,{maintainPosition:!0})},100);return!1}));window.location&&"https:"==window.location.protocol&&$(".overlay a").each(function(){if("close"===this.className||"string"!=typeof this.getAttribute("href"))return!0;var a=this.getAttribute("href");"/"==a.charAt(0)&&(a=VSD.www+a);a=a.replace(/^https:\/\//i,"http://");this.setAttribute("href",a)});$(".title-bar h1",VSD.Overlay.id).hide();$(".title-bar h1",
VSD.Overlay.id).html($(".content-inner h1",VSD.Overlay.id).html());$(".content-inner h1",VSD.Overlay.id).remove();VSD.Cufon.initOn(".title-bar",VSD.Overlay.id);$(".title-bar h1",VSD.Overlay.id).show();VSD.Overlay.callback();setTimeout(function(){VSD.UI.scrollbar(VSD.Overlay.content);$("ul.tab").each(function(){$(this).children("li:first").addClass("active")});$("ul.tab li").each(function(){if($(this).hasClass("active")){var a=$(this).find("a").attr("href"),a=a.split("#"),b=a.length;b--;a=a[b];$("#"+
a).show();VSD.UI.scrollbar(VSD.Overlay.content)}})},500)})},callback:function(){}})}
jQuery.fn.supersleight=function(a){a=jQuery.extend({imgs:!0,backgrounds:!0,shim:"x.gif",apply_positioning:!0},a);return this.each(function(){jQuery.browser.msie&&(7>parseInt(jQuery.browser.version,10)&&4<parseInt(jQuery.browser.version,10))&&jQuery(this).find("*").andSelf().each(function(e,b){var d=jQuery(b);if(a.backgrounds&&null!==d.css("background-image").match(/\.png/i)){var g=d.css("background-image"),g=g.substring(5,g.length-2),f="no-repeat"==d.css("background-repeat")?"crop":"scale",g={filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+
g+"', sizingMethod='"+f+"')","background-image":"url("+a.shim+")"};d.css(g)}a.imgs&&d.is("img[src$=png]")&&(g={width:d.width()+"px",height:d.height()+"px",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+d.attr("src")+"', sizingMethod='scale')"},d.css(g).attr("src",a.shim));a.apply_positioning&&(d.is("a, input")&&(""===d.css("position")||"static"==d.css("position")))&&d.css("position","relative")})})};
$.fn.imagesLoaded=function(a){var e=this.filter("img"),b=e.length;e.bind("load",function(){0>=--b&&a.call(e,this)}).each(function(){if(this.complete||void 0===this.complete){var a=this.src;this.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";this.src=a}});return this};
(function(a){a.fn.imgFlipper=function(e){var b=a.extend({},a.fn.imgFlipper.defaults,e);return this.each(function(){var d=a(this);d.css({position:"relative"});d.children(":not(.active)").each(function(){a(this).css({display:"none",position:"absolute",top:0,right:0})});d.children(".active").css({display:"block"});setInterval(function(){var a=d.children(".active"),e=0<a.next().length?a.next():d.children("*:first");a.fadeOut(b.fadeSpeed);e.fadeIn(b.fadeSpeed,function(){e.addClass("active").css({position:"relative",
display:"block"});a.removeClass("active").css({display:"none",position:"absolute",top:0,right:0})})},b.fadeInterval)})};a.fn.imgFlipper.defaults={fadeInterval:4E3,fadeSpeed:300}})(jQuery);
(function(a){a.fn.expandcollapse=function(e){var b={wrapper:".ui-list-expandcollapse",selfclose:!1,otherclose:!0,animationspeed:500,animation:""};e&&a.extend(b,e);return this.each(function(){var d=a(this,b.wrapper),e=d.parent().parent(),f=d.parent().siblings("div"),c=a(b.wrapper).children("li");d.hover(function(){e.addClass("hover")},function(){e.removeClass("hover")});d.click(function(){if(e.hasClass("active")){if(!0===b.selfclose){switch(b.animation){case "show":f.hide(b.animationspeed);break;case "slide":f.slideUp(b.animationspeed);
break;case "fade":f.fadeOut(b.animationspeed);break;default:f.hide()}e.removeClass("active")}}else switch(!0===b.otherclose&&c.removeClass("active"),e.addClass("active"),f.children(":first").css("margin-top","0"),b.animation){case "show":f.show(b.animationspeed);break;case "slide":f.slideDown(b.animationspeed);break;case "fade":f.fadeIn(b.animationspeed);break;default:f.show()}})})}})(jQuery);$(document).ready(function(){$("span","li>p").expandcollapse()});
(function(a){a.fn.imgSwap=function(e){var b={layout:"bottom",hoverborder:"",selectedborder:"",mainimage:"#SwapImg",mainWrapper:"#ImgSwapMain",swapeffect:"fade",tooltip:!1};return this.each(function(){var d=a(this),g=!0,f=VSD.Client.isTouch()?"touchstart":"mouseenter",c=VSD.Client.isTouch()?"touchend":"mouseleave";e&&a.extend(b,e);d.bind(f,function(){d.addClass("hover "+b.hoverborder);var c=d.children("span").children("img").attr("hiddenAlt");if(b.tooltip&&"undefined"!==typeof c&&!1!==c){var c=a(".moreinfo").offset(),
e=d.offset();a(".moreinfo").append('<div id="popup-wrapper"><div id="top-side" class="side"></div><div id="bottom-side" class="side"></div><div id="left-side" class="side"></div><div id="right-side" class="side"></div><div class="corner t-l"></div><div class="corner t-r"></div><div class="corner b-l"></div><div class="corner b-r"></div><div id="popup-content"></div></div>');a("#popup-content").html("").append("<span>"+d.children("span").children("img").attr("hiddenAlt")+"</span>");var f=(d.children("span").children("img").height()-
a("#popup-wrapper").height())/2;a("#popup-wrapper").css({left:e.left-c.left-a("#popup-wrapper").width()+6,top:e.top-c.top+f});a("#left-side,#right-side").height(a("#popup-wrapper").height()-2*a(".corner").height());VSD.Client.isIE8()||VSD.Client.isIE7()?a("#bottom-side,#top-side").width(a("#popup-wrapper").width()-2*a(".corner").width()-20):a("#bottom-side,#top-side").width(a("#popup-wrapper").width()-2*a(".corner").width());d.parent().append('<span id="small-left-border"></span>');a("#small-left-border").css({position:"absolute",
"z-index":"101",background:"#fff",width:"1px",height:a("#popup-content").height()+26,left:e.left-c.left,top:e.top-c.top+f+10});a.browser.msie&&"6.0"==a.browser.version&&a("#small-left-border").css({height:a("#popup-content").height()+24,top:e.top-c.top+f+11})}});d.bind(c,function(){d.removeClass("hover "+b.hoverborder);b.tooltip&&(0<a("#popup-wrapper").length&&0<a("#small-left-border").length)&&a("#popup-wrapper, #small-left-border").remove()});VSD.Client.isIPad()&&d.bind("touchmove",function(){d.removeClass("hover "+
b.hoverborder)});d.bind("click",function(c){c.preventDefault();c.stopPropagation();""===b.selectedborder&&(b.selectedborder=b.hoverborder);a(".item>a").removeClass("selected "+b.selectedborder);d.addClass("selected "+b.selectedborder);if(d.attr("href")===a(b.mainimage).attr("src")||!d.attr("href")||d.hasClass("notlinked"))g=!1;b.mainimage&&g&&($newMain=a(b.mainimage).clone(),$newMain.appendTo(b.mainWrapper+">.col-a").attr("src",d.attr("href")).css("display","none"),a(b.mainimage).removeAttr("id"),
$newMain.delay(50).fadeIn("fast",function(){a(".col-a>img:not('"+b.mainimage+"')",b.mainWrapper).remove()}),"bottom"===b.layout&&(c=d.children("span").children("img").attr("descid"),"undefined"!==typeof c&&!1!==c&&(a(b.mainWrapper).children(".col-b").hide(),a("#desc-"+c).show())))})})}})(jQuery);VSD.SearchAutocomplete=function(){var a,e,b,d,g,f,c,h;return{init:function(){$("#atomz_query").one("focus",function(){a=document.getElementById("sp_staged")?document.getElementById("sp_staged").value:0;e="https:"==document.location.protocol?"https:":"http:";b=a?"-stage/":"/";d=e+"//content.atomz.com/autocomplete/sp10/04/8b/28"+b+"?callback=VSD.SearchAutocomplete.callback";g=document.getElementById("searchform");f=document.getElementById("atomz_query");markup='<div class="yui-ac-content" style="display: none;"><div class="yui-ac-hd" style="display: none;"></div><div class="yui-ac-bd"><ul id="autocomplete-list"></ul></div><div class="yui-ac-ft" style="display: none; "></div></div><div class="yui-ac-shadow" style=""></div>';
c=$(markup);h=c.find("#autocomplete-list");f.setAttribute("autocomplete","off");$("#atomz_query").live("blur",function(){setTimeout(function(){c.hide()},300)});$("li",h).live({mouseover:function(){this.setAttribute("class","yui-ac-highlight")},mouseout:function(){this.setAttribute("class","")},mousedown:function(){f.value=this.innerHTML;g.submit()}});$("#atomz_query").live("keyup",function(){if(""==f.value||1==f.value.length)return!0;$.ajax({url:d,data:{max_results:10,query:f.value,callback:"VSD.SearchAutocomplete.callback"},
type:"GET",dataType:"jsonp"})});$("#autocomplete").append(c)})},callback:function(a){if(0<a.length){h.html("");for(var b=0;b<a.length;b++)h.append("<li>"+a[b]+"</li>");c.show()}}}}();VSD.SearchAutocomplete.init();
